const fs=require('fs'),assert=require('assert/strict');
const manifest=JSON.parse(fs.readFileSync('./manifest.webmanifest','utf8'));
const index=fs.readFileSync('./index.html','utf8');
assert.equal(manifest.display,'standalone');
assert.deepEqual(manifest.display_override,['standalone']);
assert.equal(manifest.prefer_related_applications,false);
assert.equal(manifest.id,'./');
assert.equal(manifest.scope,'./');
assert.match(manifest.start_url,/source=pwa/);
const sizes=new Set(manifest.icons.map(x=>x.sizes));
assert(sizes.has('192x192')&&sizes.has('512x512'));
assert(manifest.icons.some(x=>String(x.purpose||'').includes('maskable')));
assert.deepEqual(manifest.shortcuts.map(x=>x.name),['Tuner','Tunings','Tools','Stage']);
for(const shortcut of manifest.shortcuts) assert.match(shortcut.url,/source=shortcut/);
assert(index.includes("window.addEventListener('beforeinstallprompt'"));
assert(index.includes("window.addEventListener('appinstalled'"));
assert(index.includes("function applyLaunchAction()"));
assert(index.includes("view === 'stage'"));
assert(index.includes("overscroll-behavior-y:none"));
assert(index.includes("@media(display-mode:standalone)"));
console.log('PASS: Android PWA manifest, install hooks, standalone shell and launcher shortcuts');
